import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "next-themes";


import TopNav from "@/components/TopNav";
import BottomNav from "@/components/BottomNav";
import { ExerciseRankingProvider } from "@/context/RankingExercises";
import { AddAndEditToastProvider } from "@/context/Addandedittoastcontext";
import { DayToastProvider } from "@/context/DayToastContext";




const inter = Inter({subsets:['latin'],variable:'--font-sans'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, "font-sans", inter.variable)}
    suppressHydrationWarning
    title="workout"
    
    >
      <head>
        <link rel="icon" type="image/svg+xml" href="/icon-192.png" />
        <title>workout app</title>
      </head>
      <body className="min-h-full flex flex-col">
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <ExerciseRankingProvider>
            <AddAndEditToastProvider>
              <DayToastProvider>
              
          <TopNav />
          {children}
          <BottomNav />
          </DayToastProvider>
          
          </AddAndEditToastProvider>
    
          
          </ExerciseRankingProvider>
          </ThemeProvider>
      </body>
    </html>
  );
}
